name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip libffi-dev build-essential \
            libssl-dev libsqlite3-dev zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev \
            libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev libjpeg-dev libandroid-tools adb

          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build APK
        run: |
          buildozer init || true
          cp buildozer.spec buildozer.spec.backup
          buildozer android debug

      - name: Archive APK
        uses: devops-infra/action-artifact@v0.4.0
        with:
          name: PrankApp-APK
          path: bin/*.apk
