name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk
          pip install --upgrade pip buildozer cython

      - run: buildozer android debug

      - uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk
